/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public\Model\Hexagon.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Hexagon.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials.MainColor} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.BorderColor} />
    </group>
  )
}

useGLTF.preload('/Hexagon.gltf')
