/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Model/Portfolio_Scene.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Portfolio_Scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Window.geometry} material={nodes.Window.material} position={[-3.98, 1.59, 0]} scale={1.85} />
      <mesh geometry={nodes.Window_3.geometry} material={nodes.Window_3.material} position={[-3.98, 1.59, 0]} rotation={[0, 0, -Math.PI / 2]} scale={1.85} />
      <mesh geometry={nodes.Window_2.geometry} material={nodes.Window_2.material} position={[-3.98, 1.59, 0]} scale={3.17} />
      <mesh geometry={nodes.Window_Glass.geometry} material={materials['Material.003']} position={[-3.98, 1.59, 0]} rotation={[0, 0, -Math.PI / 2]} scale={1.85} />
      <mesh geometry={nodes.Couch.geometry} material={materials['Default OBJ']} position={[-1.37, -1.98, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.Room.geometry} material={nodes.Room.material} position={[-1.37, -1.98, 0]} scale={4.94} />
      <group position={[-3.15, -1.98, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02}>
        <mesh geometry={nodes.TV_Unit_Base.geometry} material={materials['TV Unit Mat']} />
        <mesh geometry={nodes.TV_Unit_Base_1.geometry} material={materials.Metal} />
      </group>
      <mesh geometry={nodes.Room_Ceiling.geometry} material={nodes.Room_Ceiling.material} position={[-1.37, -1.98, 0]} scale={4.94} />
    </group>
  )
}

useGLTF.preload('/Portfolio_Scene.gltf')
