/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Model/Sofa.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sofa.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Couch.geometry} material={materials['Default OBJ']} position={[-0.38, -1.98, -2.69]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('/Sofa.gltf')
